name: zippy
description: "Zippy"
publish_to: "none"

version: 1.0.2+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_slidable: ^3.1.0
  share_plus: ^10.1.1
  app_tracking_transparency: ^2.0.4
  flutter_naver_login: ^1.8.0
  random_avatar: ^0.0.8
  kakao_flutter_sdk_talk: ^1.9.1+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_review: ^2.0.9
  lottie: ^3.1.0
  flutter_expandable_fab: ^2.0.0
  shared_preferences: ^2.3.2
  google_mobile_ads: ^5.2.0
  url_launcher: ^6.3.1
  highlightable_text:
    path: ../highlightable_text
  kakao_flutter_sdk: ^1.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: any
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.4.0
  mockito: ^5.4.2
  flutter_markdown: ^0.7.4+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/app/icon.png"
  image_path_android: "assets/app/icon.png"
  adaptive_icon_background: "#0D121C"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app/icon.png"
  windows:
    generate: true
    image_path: "assets/app/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app/icon.png"

flutter_native_splash:
  color: "#0D121C"
  image: assets/app/icon.png
  icon_background_color: "#0D121C"
  ios_content_mode: "center"
  android_gravity: "center"
  android_12:
    icon_background_color: "#0D121C"
    image: assets/app/icon.png
    color: "#0D121C"

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.development
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/app/
    - assets/animation/
    - assets/subscription/

  fonts:
    - family: PretendardVariable
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
    - family: ChosunSm
      fonts:
        - asset: assets/fonts/ChosunSm.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900